// Writes the Serbian page, sr/index.html, from index.html and the Serbian text in i18n.js.
//
//   node tools/build-sr.mjs           write sr/index.html
//   node tools/build-sr.mjs --check   only say whether sr/index.html is up to date (exit 1 if it is not)
//
// Run it after any change to index.html or i18n.js, and commit sr/index.html with them. It needs Node 18 or later and
// nothing else.
//
// What changes on the way, and nothing more:
// - every marked text takes its Serbian: data-i18n the element's whole content (it may hold markup), data-i18n-text
//   the element's own text (its first text that is more than space), data-i18n-alt, -aria-label and -content the
//   attribute. A mark with no Serbian stays English.
// - <html lang> is sr-Latn, the language button shows SR, and the menu checks Srpski.
// - addresses inside the site are written from sr/ (../styles.css, ../assets/...); #anchors and full addresses stay.
// - the canonical address and og:url are https://assetprompter.com/sr/. The hreflang links stay: both pages name both.
// - the fonts' latin-ext files are preloaded with the latin ones, for the letters with marks.
// - the JSON-LD takes the Serbian of every text it copies from the page, and of the features (ld.feature.N); the
//   page's own nodes (WebPage, FAQPage) move to /sr/ and say "inLanguage": "sr-Latn". It stops if one of the texts it
//   should copy is not on the page any more.
// - the few texts main.js writes itself (say("key", ...)) go in as a small JSON block, #say.

import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SITE = "https://assetprompter.com/";
const PAGE = "https://assetprompter.com/sr/";
const DIR = "/sr/";
const TAG = "sr-Latn";
const CODE = "SR";
const ATTRS = ["alt", "aria-label", "content"];
const URL_ATTRS = new Set(["href", "src", "srcset", "poster", "data-video", "data-src", "data-poster", "imagesrcset", "action"]);
// The nodes of the JSON-LD that describe this page rather than the site, the app or the author.
const PAGE_TYPES = new Set(["WebPage", "FAQPage", "Question", "Answer", "HowTo", "HowToStep", "BreadcrumbList"]);
// The JSON-LD keys whose values are texts a reader could see on the page; names of things, kinds and addresses stay.
const TEXT_KEYS = new Set(["name", "description", "text", "headline", "alternativeHeadline", "abstract", "caption"]);
const VOID = new Set(["area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source", "track", "wbr"]);
const HEADER = "<!-- generated by tools/build-sr.mjs — do not edit: change index.html or i18n.js and run it again -->";

const read = (file) => fs.readFileSync(path.join(ROOT, file), "utf8");

/** The SR object of i18n.js, run in an empty sandbox: the file only declares it. */
function serbian() {
  const sandbox = vm.createContext({});
  const SR = new vm.Script(`${read("i18n.js")}\n;SR`, { filename: "i18n.js" }).runInContext(sandbox, { timeout: 1000 });
  if (!SR || typeof SR !== "object") throw new Error("i18n.js has no SR object");
  // Out of the sandbox, as plain strings.
  return Object.fromEntries(Object.entries(SR).map(([key, value]) => [key, String(value)]));
}

/* ---- a small reader for the page's own HTML: elements, their attributes and where each starts and ends ---- */

const TAG_RE = /<(\/?)([a-zA-Z][\w:-]*)((?:\s+[^\s"'>\/=]+(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s"'=<>`]+))?)*)\s*(\/?)>/y;
const ATTR_RE = /([^\s"'>\/=]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+)))?/g;

function parse(html) {
  const top = { name: "#root", attrs: [], children: [] };
  const stack = [top];
  let i = 0;
  let text = 0;
  const flush = (end) => {
    if (end > text) stack.at(-1).children.push({ text: true, start: text, end });
  };
  while (i < html.length) {
    const lt = html.indexOf("<", i);
    if (lt < 0) break;
    if (html.startsWith("<!--", lt)) {
      const end = html.indexOf("-->", lt + 4);
      if (end < 0) throw new Error(`unclosed comment at ${lt}`);
      flush(lt);
      i = text = end + 3;
      continue;
    }
    if (html.startsWith("<!", lt)) {
      flush(lt);
      i = text = html.indexOf(">", lt) + 1;
      continue;
    }
    TAG_RE.lastIndex = lt;
    const m = TAG_RE.exec(html);
    if (!m) {
      i = lt + 1;
      continue;
    }
    flush(lt);
    const [whole, closing, rawName, rawAttrs, selfClosing] = m;
    const name = rawName.toLowerCase();
    i = text = lt + whole.length;
    if (closing) {
      const open = stack.pop();
      if (open.name !== name) throw new Error(`</${name}> at ${lt} closes <${open.name}> opened at ${open.start}`);
      open.contentEnd = lt;
      open.end = i;
      continue;
    }
    const attrs = [];
    const base = lt + 1 + rawName.length;
    for (const a of rawAttrs.matchAll(ATTR_RE)) {
      const value = a[2] ?? a[3] ?? a[4];
      const at = base + a.index;
      // Where the value itself starts and ends, without its quotes.
      const vEnd = value === undefined ? null : at + a[0].length - (a[4] === undefined ? 1 : 0);
      attrs.push({ name: a[1].toLowerCase(), value: value ?? "", start: at, end: at + a[0].length, vStart: vEnd === null ? null : vEnd - value.length, vEnd });
    }
    const el = { name, attrs, start: lt, tagEnd: i, contentStart: i, children: [] };
    stack.at(-1).children.push(el);
    if (VOID.has(name) || selfClosing) {
      el.contentEnd = el.end = i;
      continue;
    }
    if (name === "script" || name === "style") {
      const end = html.toLowerCase().indexOf(`</${name}`, i);
      el.contentEnd = end;
      el.end = html.indexOf(">", end) + 1;
      i = text = el.end;
      continue;
    }
    stack.push(el);
  }
  flush(html.length);
  if (stack.length > 1) throw new Error(`<${stack.at(-1).name}> opened at ${stack.at(-1).start} is never closed`);
  return top;
}

function* walk(node) {
  for (const child of node.children) {
    if (child.text) continue;
    yield child;
    yield* walk(child);
  }
}

const attr = (el, name) => el.attrs.find((a) => a.name === name);
const hasClass = (el, name) => (attr(el, "class")?.value ?? "").split(/\s+/).includes(name);

/* ---- texts ---- */

const ENTITIES = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " " };
const decode = (s) =>
  s.replace(/&(#x[\da-f]+|#\d+|[a-z]+);/gi, (all, e) => {
    if (e[0] === "#") return String.fromCodePoint(e[1] === "x" || e[1] === "X" ? parseInt(e.slice(2), 16) : Number(e.slice(1)));
    if (!(e in ENTITIES)) throw new Error(`unknown entity ${all}`);
    return ENTITIES[e];
  });
const escapeText = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const escapeAttr = (s) => s.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
/** Markup as a reader sees it: no tags, entities read, space as one space. */
const plain = (html) => decode(html.replace(/<[^>]*>/g, "")).replace(/\s+/g, " ").trim();

/** An address inside the site, written as seen from sr/. */
function fromSr(url) {
  if (!url || /^(#|\/|[a-z][a-z\d+.-]*:|\?)/i.test(url)) return url;
  const u = new URL(url, "https://site/");
  let rel = path.posix.relative(DIR, u.pathname);
  if (u.pathname.endsWith("/") && rel) rel += "/";
  return (rel || "./") + u.search + u.hash;
}

/* ---- the JSON-LD ---- */

function translateLd(json, english, SR) {
  const data = JSON.parse(json);
  const graph = data["@graph"] ?? [data];
  // The @id of each node that describes this page moves to /sr/, wherever it is named.
  const ids = new Map();
  for (const node of graph) {
    if (PAGE_TYPES.has(node["@type"]) && node["@id"]?.startsWith(SITE + "#")) ids.set(node["@id"], PAGE + node["@id"].slice(SITE.length));
  }
  const missing = [];
  const left = [];
  const features = Object.keys(SR)
    .filter((key) => /^ld\.feature\.\d+$/.test(key))
    .sort((a, b) => a.split(".")[2] - b.split(".")[2])
    .map((key) => SR[key]);

  function visit(value, key, owner) {
    if (Array.isArray(value)) {
      if (key === "featureList") {
        if (value.length !== features.length) throw new Error(`featureList has ${value.length} features, i18n.js has ${features.length} (ld.feature.N)`);
        return features;
      }
      return value.map((item) => visit(item, key, owner));
    }
    if (value && typeof value === "object") {
      const out = {};
      for (const [k, v] of Object.entries(value)) out[k] = visit(v, k, value);
      return out;
    }
    if (typeof value !== "string") return value;
    if (ids.has(value)) return ids.get(value);
    const type = owner["@type"];
    if (key === "inLanguage" && PAGE_TYPES.has(type)) return TAG;
    if (key === "url" && value === SITE && PAGE_TYPES.has(type)) return PAGE;
    if (!TEXT_KEYS.has(key)) return value;
    const sr = english.get(value.replace(/\s+/g, " ").trim());
    if (sr !== undefined) return sr;
    // These are the page's own texts: each must still be one.
    const copied = { WebPage: ["name", "description"], SoftwareApplication: ["description"], Question: ["name"], Answer: ["text"] };
    if (copied[type]?.includes(key)) missing.push(`${type} ${key}: ${value}`);
    else if (value.split(" ").length > 4) left.push(`${type} ${key}: ${value}`);
    return value;
  }

  const out = visit(data, "", {});
  if (missing.length) throw new Error(`the JSON-LD copies texts that are not on the page; make them the page's again:\n  ${missing.join("\n  ")}`);
  for (const text of left) console.warn(`build-sr: left in English in the JSON-LD (no element has this text): ${text}`);
  return out;
}

/* ---- the page ---- */

function build() {
  const html = read("index.html");
  const SR = serbian();
  const doc = parse(html);
  const edits = [];
  const edit = (start, end, text) => edits.push({ start, end, text });
  const setAttr = (el, name, value) => {
    const a = attr(el, name);
    if (!a) edit(el.tagEnd - (html[el.tagEnd - 2] === "/" ? 2 : 1), el.tagEnd - (html[el.tagEnd - 2] === "/" ? 2 : 1), ` ${name}="${escapeAttr(value)}"`);
    else if (a.vStart === null) edit(a.end, a.end, `="${escapeAttr(value)}"`);
    else edit(a.vStart, a.vEnd, escapeAttr(value));
  };
  // English and Serbian of every marked text, for the JSON-LD.
  const english = new Map();
  const pair = (key, en) => {
    if (SR[key] !== undefined) english.set(plain(en), plain(SR[key]));
  };
  const unknown = new Set();
  const say = (key) => {
    if (SR[key] === undefined) unknown.add(key);
    return SR[key];
  };

  const elements = [...walk(doc)];
  for (const el of elements) {
    const key = attr(el, "data-i18n")?.value;
    if (key !== undefined) {
      pair(key, html.slice(el.contentStart, el.contentEnd));
      if (say(key) !== undefined) edit(el.contentStart, el.contentEnd, SR[key]);
    }
  }
  for (const el of elements) {
    const key = attr(el, "data-i18n-text")?.value;
    if (key === undefined) continue;
    const node = el.children.find((c) => c.text && html.slice(c.start, c.end).trim());
    if (!node) continue;
    const raw = html.slice(node.start, node.end);
    pair(key, raw);
    if (say(key) === undefined) continue;
    // The space around the text stays: it is what separates it from the next element.
    const [, before, after] = /^(\s*)[\s\S]*?(\s*)$/.exec(raw);
    edit(node.start + before.length, node.end - after.length, escapeText(SR[key]));
  }
  for (const name of ATTRS) {
    for (const el of elements) {
      const key = attr(el, `data-i18n-${name}`)?.value;
      if (key === undefined) continue;
      pair(key, attr(el, name)?.value ?? "");
      if (say(key) !== undefined) setAttr(el, name, SR[key]);
    }
  }

  let ldDone = false;
  let sayDone = false;
  const sayKeys = [...new Set([...read("main.js").matchAll(/\bsay\(\s*"([^"]+)"/g)].map((m) => m[1]))];
  for (const el of elements) {
    const rel = attr(el, "rel")?.value;
    const property = attr(el, "property")?.value;
    if (el.name === "html") setAttr(el, "lang", TAG);
    if (hasClass(el, "lang-code")) edit(el.contentStart, el.contentEnd, CODE);
    if (attr(el, "data-lang") && attr(el, "aria-checked")) setAttr(el, "aria-checked", String(attr(el, "data-lang").value === "sr"));
    if (el.name === "link" && rel === "canonical") setAttr(el, "href", PAGE);
    if (el.name === "meta" && property === "og:url") setAttr(el, "content", PAGE);
    // The latin-ext file of a preloaded font goes right after it.
    const href = attr(el, "href")?.value ?? "";
    if (el.name === "link" && rel === "preload" && /-latin\.woff2$/.test(href)) {
      const tag = html.slice(el.start, el.tagEnd).replace(href, fromSr(href.replace(/-latin\.woff2$/, "-latin-ext.woff2")));
      const indent = /[ \t]*$/.exec(html.slice(0, el.start))[0];
      edit(el.tagEnd, el.tagEnd, `\n${indent}${tag}`);
    }
    for (const a of el.attrs) {
      if (!URL_ATTRS.has(a.name) || a.vStart === null || (el.name === "link" && rel === "canonical")) continue;
      const value = a.name.endsWith("srcset")
        ? a.value
            .split(",")
            .map((part) => part.replace(/^(\s*)(\S+)/, (all, space, url) => space + fromSr(url)))
            .join(",")
        : fromSr(a.value);
      if (value !== a.value) edit(a.vStart, a.vEnd, value);
    }
    if (el.name === "script" && attr(el, "type")?.value === "application/ld+json") {
      const indent = /[ \t]*$/.exec(html.slice(0, el.start))[0] + "  ";
      const ld = JSON.stringify(translateLd(html.slice(el.contentStart, el.contentEnd), english, SR), null, 2).replace(/<\//g, "<\\/");
      edit(el.contentStart, el.contentEnd, `\n${ld.replace(/^/gm, indent)}\n${indent.slice(2)}`);
      ldDone = true;
    }
    // The texts main.js writes itself, just before main.js.
    if (el.name === "script" && /(^|\/)main\.js(\?|$)/.test(attr(el, "src")?.value ?? "")) {
      const texts = Object.fromEntries(sayKeys.filter((key) => say(key) !== undefined).map((key) => [key, SR[key]]));
      const indent = /[ \t]*$/.exec(html.slice(0, el.start))[0];
      edit(el.start, el.start, `<script type="application/json" id="say">${JSON.stringify(texts).replace(/<\//g, "<\\/")}</script>\n${indent}`);
      sayDone = true;
    }
  }
  if (!ldDone) throw new Error("index.html has no JSON-LD block");
  if (!sayDone) throw new Error("index.html does not load main.js");

  edits.sort((a, b) => a.start - b.start || a.end - b.end);
  for (let n = 1; n < edits.length; n++) {
    if (edits[n].start < edits[n - 1].end) throw new Error(`two changes overlap at ${edits[n].start}: is a marked text inside another?`);
  }
  let out = "";
  let at = 0;
  for (const e of edits) {
    out += html.slice(at, e.start) + e.text;
    at = e.end;
  }
  out += html.slice(at);
  out = out.replace(/^(<!doctype html>\n)/i, `$1${HEADER}\n`);
  if (!out.includes(HEADER)) out = `${HEADER}\n${out}`;
  if (unknown.size) console.warn(`build-sr: no Serbian in i18n.js, left in English: ${[...unknown].join(", ")}`);
  return out;
}

const target = path.join(ROOT, "sr", "index.html");
const page = build();
if (process.argv.includes("--check")) {
  const now = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
  if (now !== page) {
    console.error("sr/index.html is out of date: run node tools/build-sr.mjs and commit it");
    process.exit(1);
  }
  console.log("sr/index.html is up to date");
} else {
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, page);
  console.log(`wrote sr/index.html (${Buffer.byteLength(page)} bytes)`);
}
